# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: findmyips 1.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "aws-ec2-instance_types"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christo De Lange"]
  s.date = "2013-10-14"
  s.description = "Retrieve an up to date list of valid AWS EC2 Instance Types"
  s.email = "github@dldinternet.com"
  s.executables = ["findmyips", "findmyips.sh"]
  s.extra_rdoc_files = [
      "LICENSE.txt",
      "README.rdoc"
  ]
  s.files = [
      ".document",
      ".rspec",
      ".ruby-gemset",
      ".ruby-version",
      "Gemfile",
      "Gemfile.lock",
      "LICENSE.txt",
      "README.rdoc",
      "Rakefile",
      "VERSION",
      "bin/aws-ec2-instance_types",
      "features/step_definitions/aws-ec2-instance_types.rb",
      "features/support/env.rb",
      "aws-ec2-instance_types.gemspec",
      "lib/dldinternet/aws/ec2/instance_types.rb",
      "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/dldinternet/aws-ec2-instance_types"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.5"
  s.summary = "Obtain my public and internal IP addresses"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<colorize>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<colorize>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<colorize>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, ["> 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

